/* ============================================================
   THROUGHLINE — Fictional case dataset (sample data)
   Cedar Hollow / Cogwheel Collectibles incident.
   Every name, org, and event here is invented for this demo.
   ============================================================ */
window.DB = (function () {
  const CATS = {
    video: { label: "Videos", cls: "video" },
    document: { label: "Documents", cls: "document" },
    police: { label: "Police Activity", cls: "police" },
    legal: { label: "Legal Filings", cls: "legal" },
    social: { label: "Social Media", cls: "social" },
    press: { label: "Press Coverage", cls: "press" },
  };

  const stats = [
    { n: "34", label: "Videos archived", x: "4 sources" },
    { n: "27", label: "Documents", x: "OCR-indexed" },
    { n: "15", label: "Timeline events", x: "Mar–May 2025" },
    { n: "128", label: "Social posts", x: "6 platforms" },
    { n: "6", label: "Bodycam files", x: "FOIA-released" },
    { n: "11", label: "People involved", x: "public roles" },
  ];

  // ---------- PEOPLE ----------
  const people = [
    {
      id: "reese-avila",
      name: "Reese Avila",
      role: "Independent content creator",
      org: "Curb Authority (YouTube)",
      side: "creator",
      verified: true,
      bio: 'Operates the "Curb Authority" channel documenting public-space and consumer disputes. Central figure in the March 2025 Cogwheel filming incident. Filed a civil complaint in Hollow County Superior Court.',
      events: ["e1", "e3", "e5", "e9", "e10"],
    },
    {
      id: "dana-whitlock",
      name: "Dana Whitlock",
      role: "Franchise owner",
      org: "Cogwheel Collectibles — Cedar Hollow",
      side: "business",
      verified: true,
      bio: "Owner-operator of the Cedar Hollow Cogwheel Collectibles franchise location. Issued the no-trespass notice and is named in the civil complaint. Represented by Whitlock & Stone LLP.",
      events: ["e1", "e2", "e3", "e9", "e11"],
    },
    {
      id: "marcus-reyes",
      name: "Marcus Reyes",
      role: "VP, Communications",
      org: "Cogwheel Brands Inc.",
      side: "business",
      verified: true,
      bio: "Corporate spokesperson for Cogwheel Brands Inc., the franchisor. Authored the March 14 corporate statement distancing the brand from the individual franchise dispute.",
      events: ["e6"],
    },
    {
      id: "officer-pruitt",
      name: "Officer J. Pruitt",
      role: "Patrol officer",
      org: "Cedar Hollow Police Dept.",
      side: "official",
      verified: true,
      bio: "Primary responding officer to the March 12 call. Bodycam unit 4471. Named in subsequent FOIA release of dispatch and body-worn camera footage.",
      events: ["e3", "e4", "e13"],
    },
    {
      id: "officer-stamper",
      name: "Officer L. Stamper",
      role: "Patrol officer",
      org: "Cedar Hollow Police Dept.",
      side: "official",
      verified: true,
      bio: "Second responding officer on the March 12 call. Bodycam unit 4490; footage released under the April 30 FOIA request.",
      events: ["e3", "e13"],
    },
    {
      id: "chief-cole",
      name: "Chief Renata Cole",
      role: "Chief of Police",
      org: "Cedar Hollow Police Dept.",
      side: "official",
      verified: true,
      bio: "Head of the Cedar Hollow Police Department. Issued a public statement on the department's handling of the incident and the FOIA disclosure process.",
      events: ["e7", "e13"],
    },
    {
      id: "da-brandt",
      name: "DA Theo Brandt",
      role: "District Attorney",
      org: "Hollow County",
      side: "official",
      verified: true,
      bio: "Hollow County District Attorney. Office reviewed the incident report and announced on April 16 that no criminal charges would be filed.",
      events: ["e12"],
    },
    {
      id: "priya-nandakumar",
      name: "Priya Nandakumar",
      role: "Attorney for R. Avila",
      org: "Nandakumar Civil Rights Law",
      side: "creator",
      verified: true,
      bio: "Civil-rights attorney representing Reese Avila. Filed the March 25 civil complaint and responded to the Cogwheel cease-and-desist.",
      events: ["e9", "e11"],
    },
    {
      id: "sam-okafor",
      name: "Sam Okafor",
      role: "Staff reporter",
      org: "The Cedar Hollow Courier",
      side: "press",
      verified: true,
      bio: "Local-news reporter who produced the first independent coverage of the incident and obtained several documents via public-records request.",
      events: ["e8", "e13"],
    },
    {
      id: "whitlock-stone",
      name: "Whitlock & Stone LLP",
      role: "Counsel for Cogwheel franchise",
      org: "Law firm",
      side: "business",
      verified: true,
      org_flag: true,
      bio: "Law firm representing the Cedar Hollow Cogwheel franchise. Issued the April 9 cease-and-desist and counter-statement.",
      events: ["e11"],
    },
    {
      id: "cogwheel-brands",
      name: "Cogwheel Brands Inc.",
      role: "Franchisor / parent company",
      org: "Corporate entity",
      side: "business",
      verified: true,
      org_flag: true,
      bio: "National franchisor of Cogwheel Collectibles stores. Released a corporate statement and a short public video addressing the incident.",
      events: ["e6"],
    },
  ];

  // ---------- TIMELINE EVENTS ----------
  const events = [
    {
      id: "e1",
      date: "2025-03-04",
      title: "Initial in-store recording posted",
      cats: ["video", "social"],
      desc: "Reese Avila posts a recording filmed inside the Cedar Hollow Cogwheel Collectibles store, sparking a dispute over the store's filming policy. The clip circulates rapidly on social platforms.",
      people: ["reese-avila", "dana-whitlock"],
      rel: { videos: 2, docs: 0, social: 14, bodycam: 0 },
    },
    {
      id: "e2",
      date: "2025-03-05",
      title: "Store issues no-trespass notice",
      cats: ["document"],
      desc: "The franchise location issues a written no-trespass notice to Avila. The notice later appears in the documents archive as part of the civil filing exhibits.",
      people: ["dana-whitlock"],
      rel: { videos: 0, docs: 1, social: 3, bodycam: 0 },
    },
    {
      id: "e3",
      date: "2025-03-12",
      title: "Police respond to reported disturbance",
      cats: ["police", "social"],
      desc: "A 911 call brings Cedar Hollow PD officers to the store. Two units respond; body-worn cameras record the interaction. No arrests are made at the scene.",
      people: [
        "officer-pruitt",
        "officer-stamper",
        "reese-avila",
        "dana-whitlock",
      ],
      rel: { videos: 1, docs: 1, social: 22, bodycam: 4 },
    },
    {
      id: "e4",
      date: "2025-03-12",
      title: "Bodycam — Unit 4471 (Pruitt) response",
      cats: ["police"],
      desc: "Body-worn camera footage from the primary responding officer, later released under the April 30 FOIA request. Runtime 14:22.",
      people: ["officer-pruitt"],
      rel: { videos: 0, docs: 0, social: 0, bodycam: 1 },
    },
    {
      id: "e5",
      date: "2025-03-13",
      title: "Avila posts follow-up account",
      cats: ["video", "social"],
      desc: 'Avila publishes a 22-minute "what really happened" video recounting the incident from their perspective, which becomes the most-viewed item in the archive.',
      people: ["reese-avila"],
      rel: { videos: 1, docs: 0, social: 31, bodycam: 0 },
    },
    {
      id: "e6",
      date: "2025-03-14",
      title: "Cogwheel Brands corporate statement",
      cats: ["document", "video", "press"],
      desc: "Cogwheel Brands Inc. releases a written statement and short video distancing the national brand from the individual franchise dispute and citing an internal review.",
      people: ["marcus-reyes", "cogwheel-brands"],
      rel: { videos: 1, docs: 1, social: 9, bodycam: 0 },
    },
    {
      id: "e7",
      date: "2025-03-18",
      title: "Police incident report released",
      cats: ["document", "police"],
      desc: "Cedar Hollow PD releases the redacted incident report. Chief Cole issues a brief statement on the department's handling of the call.",
      people: ["chief-cole", "officer-pruitt"],
      rel: { videos: 0, docs: 2, social: 6, bodycam: 0 },
    },
    {
      id: "e8",
      date: "2025-03-20",
      title: "First independent news coverage",
      cats: ["press", "video"],
      desc: "The Cedar Hollow Courier publishes the first independent report, adding sourced context and a documents request that surfaces additional records.",
      people: ["sam-okafor"],
      rel: { videos: 1, docs: 1, social: 11, bodycam: 0 },
    },
    {
      id: "e9",
      date: "2025-03-25",
      title: "Avila files civil complaint",
      cats: ["legal", "document"],
      desc: "Attorney Priya Nandakumar files a civil complaint in Hollow County Superior Court naming the franchise owner. The complaint and exhibits enter the documents archive.",
      people: ["priya-nandakumar", "reese-avila", "dana-whitlock"],
      rel: { videos: 0, docs: 3, social: 18, bodycam: 0 },
    },
    {
      id: "e10",
      date: "2025-04-02",
      title: "Legal fund launched",
      cats: ["social"],
      desc: "A public fundraiser for Avila's legal costs launches and circulates widely across platforms. Linked from the archive header.",
      people: ["reese-avila"],
      rel: { videos: 0, docs: 0, social: 24, bodycam: 0 },
    },
    {
      id: "e11",
      date: "2025-04-09",
      title: "Cogwheel counsel issues cease-and-desist",
      cats: ["legal", "document"],
      desc: "Whitlock & Stone LLP issues a cease-and-desist and counter-statement on behalf of the franchise. Nandakumar responds publicly the same week.",
      people: ["whitlock-stone", "dana-whitlock", "priya-nandakumar"],
      rel: { videos: 0, docs: 2, social: 7, bodycam: 0 },
    },
    {
      id: "e12",
      date: "2025-04-16",
      title: "District Attorney declines to file charges",
      cats: ["legal", "document", "press"],
      desc: "The Hollow County DA's office announces that, after reviewing the incident report, it will not pursue criminal charges related to the March 12 call.",
      people: ["da-brandt"],
      rel: { videos: 0, docs: 1, social: 13, bodycam: 0 },
    },
    {
      id: "e13",
      date: "2025-04-30",
      title: "FOIA release: dispatch logs + bodycam",
      cats: ["document", "police"],
      desc: "A public-records request returns full dispatch logs and both officers' body-worn camera footage. Reporter Sam Okafor publishes an annotated index.",
      people: ["officer-pruitt", "officer-stamper", "chief-cole", "sam-okafor"],
      rel: { videos: 0, docs: 4, social: 8, bodycam: 5 },
    },
    {
      id: "e14",
      date: "2025-05-08",
      title: "Independent analysts publish breakdowns",
      cats: ["video", "press"],
      desc: "Several independent commentators and a legal analyst publish timeline breakdowns synthesizing the released footage and filings.",
      people: [],
      rel: { videos: 6, docs: 0, social: 19, bodycam: 0 },
    },
    {
      id: "e15",
      date: "2025-05-20",
      title: "City council public-comment session",
      cats: ["video", "press"],
      ongoing: true,
      desc: "The incident is raised during a Cedar Hollow city-council public-comment period regarding filming policy on commercial premises. Proceedings are ongoing.",
      people: ["chief-cole"],
      rel: { videos: 2, docs: 1, social: 9, bodycam: 0 },
    },
  ];

  // ---------- VIDEOS ----------
  const videos = [
    // tier: creator / official / business / coverage
    {
      id: "v1",
      tier: "creator",
      title: "Filming policy dispute at Cogwheel Collectibles — full clip",
      source: "Curb Authority",
      platform: "YouTube",
      date: "2025-03-04",
      dur: "17:41",
      views: "2.4M",
      event: "e1",
    },
    {
      id: "v2",
      tier: "creator",
      title: "What really happened — my full account",
      source: "Curb Authority",
      platform: "YouTube",
      date: "2025-03-13",
      dur: "22:08",
      views: "3.9M",
      event: "e5",
    },
    {
      id: "v3",
      tier: "creator",
      title: "Reading the police report on camera",
      source: "Curb Authority",
      platform: "YouTube",
      date: "2025-03-18",
      dur: "19:55",
      views: "1.6M",
      event: "e7",
    },
    {
      id: "v4",
      tier: "creator",
      title: "We filed the lawsuit — here's the complaint",
      source: "Curb Authority",
      platform: "YouTube",
      date: "2025-03-25",
      dur: "15:30",
      views: "1.1M",
      event: "e9",
    },
    {
      id: "v5",
      tier: "creator",
      title: "Going through the FOIA bodycam footage",
      source: "Curb Authority",
      platform: "YouTube",
      date: "2025-04-30",
      dur: "28:12",
      views: "2.0M",
      event: "e13",
    },
    {
      id: "v6",
      tier: "creator",
      title: "Update: the DA's decision",
      source: "Curb Authority",
      platform: "YouTube",
      date: "2025-04-16",
      dur: "11:47",
      views: "980K",
      event: "e12",
    },

    {
      id: "v7",
      tier: "official",
      title: "Cedar Hollow PD — Unit 4471 body-worn camera (FOIA)",
      source: "Cedar Hollow PD",
      platform: "Records portal",
      date: "2025-04-30",
      dur: "14:22",
      views: "—",
      event: "e4",
      official: true,
    },
    {
      id: "v8",
      tier: "official",
      title: "Cedar Hollow PD — Unit 4490 body-worn camera (FOIA)",
      source: "Cedar Hollow PD",
      platform: "Records portal",
      date: "2025-04-30",
      dur: "09:38",
      views: "—",
      event: "e13",
      official: true,
    },
    {
      id: "v9",
      tier: "official",
      title: "Chief Cole — statement on the March 12 response",
      source: "Cedar Hollow PD",
      platform: "Records portal",
      date: "2025-03-18",
      dur: "04:11",
      views: "—",
      event: "e7",
      official: true,
    },
    {
      id: "v10",
      tier: "official",
      title: "Hollow County DA — charging decision briefing",
      source: "Hollow County DA",
      platform: "Records portal",
      date: "2025-04-16",
      dur: "06:54",
      views: "—",
      event: "e12",
      official: true,
    },

    {
      id: "v11",
      tier: "business",
      title: "Cogwheel Brands — official statement",
      source: "Cogwheel Brands Inc.",
      platform: "YouTube",
      date: "2025-03-14",
      dur: "02:38",
      views: "420K",
      event: "e6",
    },
    {
      id: "v12",
      tier: "business",
      title: "Franchise filming policy — explainer",
      source: "Cogwheel Brands Inc.",
      platform: "YouTube",
      date: "2025-03-21",
      dur: "03:12",
      views: "190K",
      event: "e6",
    },
    {
      id: "v13",
      tier: "business",
      title: "Whitlock & Stone — counsel statement",
      source: "Whitlock & Stone LLP",
      platform: "Press release",
      date: "2025-04-09",
      dur: "05:02",
      views: "88K",
      event: "e11",
    },

    {
      id: "v14",
      tier: "coverage",
      title: "Cedar Hollow Courier — the incident, explained",
      source: "The Cedar Hollow Courier",
      platform: "YouTube",
      date: "2025-03-20",
      dur: "08:44",
      views: "610K",
      event: "e8",
    },
    {
      id: "v15",
      tier: "coverage",
      title: "Legal analyst: what the complaint actually claims",
      source: "Brandt-free Law Review",
      platform: "YouTube",
      date: "2025-03-27",
      dur: "24:19",
      views: "1.3M",
      event: "e9",
    },
    {
      id: "v16",
      tier: "coverage",
      title: "Frame-by-frame: the bodycam timeline",
      source: "Open Footage",
      platform: "YouTube",
      date: "2025-05-08",
      dur: "31:06",
      views: "870K",
      event: "e14",
    },
    {
      id: "v17",
      tier: "coverage",
      title: "Why this case went viral — a media breakdown",
      source: "Signal & Noise",
      platform: "YouTube",
      date: "2025-05-10",
      dur: "18:23",
      views: "540K",
      event: "e14",
    },
    {
      id: "v18",
      tier: "coverage",
      title: "City council weighs filming-policy rules",
      source: "The Cedar Hollow Courier",
      platform: "YouTube",
      date: "2025-05-20",
      dur: "12:50",
      views: "160K",
      event: "e15",
    },
  ];

  // ---------- BODYCAM ----------
  const bodycam = [
    {
      id: "b1",
      title: "Unit 4471 — primary response, store entrance",
      officer: "Officer J. Pruitt",
      unit: "4471",
      date: "2025-03-12",
      time: "18:42",
      dur: "14:22",
      location: "Cogwheel Collectibles, 1400 Maple St.",
      type: "Disturbance call",
      event: "e4",
      released: "2025-04-30",
    },
    {
      id: "b2",
      title: "Unit 4490 — secondary response, sidewalk",
      officer: "Officer L. Stamper",
      unit: "4490",
      date: "2025-03-12",
      time: "18:47",
      dur: "09:38",
      location: "1400 Maple St. (exterior)",
      type: "Disturbance call",
      event: "e13",
      released: "2025-04-30",
    },
    {
      id: "b3",
      title: "Unit 4471 — statement collection",
      officer: "Officer J. Pruitt",
      unit: "4471",
      date: "2025-03-12",
      time: "19:05",
      dur: "07:51",
      location: "1400 Maple St. (parking lot)",
      type: "Witness statements",
      event: "e13",
      released: "2025-04-30",
    },
    {
      id: "b4",
      title: "Unit 4490 — dispatch return",
      officer: "Officer L. Stamper",
      unit: "4490",
      date: "2025-03-12",
      time: "19:20",
      dur: "03:14",
      location: "En route",
      type: "Clear scene",
      event: "e13",
      released: "2025-04-30",
    },
    {
      id: "b5",
      title: "Unit 4471 — follow-up visit",
      officer: "Officer J. Pruitt",
      unit: "4471",
      date: "2025-03-15",
      time: "11:10",
      dur: "06:39",
      location: "Cogwheel Collectibles, 1400 Maple St.",
      type: "Follow-up",
      event: "e13",
      released: "2025-04-30",
    },
    {
      id: "b6",
      title: "Unit 4471 — report supplement",
      officer: "Officer J. Pruitt",
      unit: "4471",
      date: "2025-03-15",
      time: "11:40",
      dur: "02:58",
      location: "Precinct 3",
      type: "Administrative",
      event: "e13",
      released: "2025-04-30",
    },
  ];

  // ---------- DOCUMENTS ----------
  const documents = [
    {
      id: "d1",
      title: "No-trespass notice issued to R. Avila",
      type: "Legal Notice",
      source: "Cogwheel Collectibles",
      date: "2025-03-05",
      pages: 2,
      event: "e2",
      tags: ["notice", "franchise"],
      summary:
        "Written no-trespass notice issued by the franchise to the named individual, later filed as a complaint exhibit.",
    },
    {
      id: "d2",
      title: "Cedar Hollow PD incident report #25-04471",
      type: "Police Report",
      source: "Cedar Hollow PD",
      date: "2025-03-18",
      pages: 6,
      event: "e7",
      tags: ["incident", "redacted"],
      summary:
        "Redacted narrative incident report from the March 12 response, including officer narratives and call metadata.",
    },
    {
      id: "d3",
      title: "Cogwheel Brands Inc. — corporate statement",
      type: "Statement",
      source: "Cogwheel Brands Inc.",
      date: "2025-03-14",
      pages: 1,
      event: "e6",
      tags: ["corporate", "statement"],
      summary:
        "One-page corporate statement on the franchise dispute and internal review.",
    },
    {
      id: "d4",
      title: "Civil complaint — Avila v. Whitlock (Exhibits A–C)",
      type: "Court Filing",
      source: "Hollow County Superior Court",
      date: "2025-03-25",
      pages: 24,
      event: "e9",
      tags: ["complaint", "exhibits", "civil"],
      summary:
        "Civil complaint and attached exhibits filed in Hollow County Superior Court.",
    },
    {
      id: "d5",
      title: "Summons and case docket sheet",
      type: "Court Filing",
      source: "Hollow County Superior Court",
      date: "2025-03-25",
      pages: 3,
      event: "e9",
      tags: ["docket", "civil"],
      summary: "Initial docket sheet and summons for the civil matter.",
    },
    {
      id: "d6",
      title: "Cease-and-desist letter",
      type: "Correspondence",
      source: "Whitlock & Stone LLP",
      date: "2025-04-09",
      pages: 4,
      event: "e11",
      tags: ["c&d", "counsel"],
      summary:
        "Cease-and-desist and counter-statement issued on behalf of the franchise.",
    },
    {
      id: "d7",
      title: "Response to cease-and-desist",
      type: "Correspondence",
      source: "Nandakumar Civil Rights Law",
      date: "2025-04-12",
      pages: 3,
      event: "e11",
      tags: ["response", "counsel"],
      summary: "Reply letter from Avila's counsel.",
    },
    {
      id: "d8",
      title: "DA charging-decision memorandum",
      type: "Legal Notice",
      source: "Hollow County DA",
      date: "2025-04-16",
      pages: 2,
      event: "e12",
      tags: ["da", "decision"],
      summary:
        "Memorandum declining to file criminal charges arising from the March 12 call.",
    },
    {
      id: "d9",
      title: "FOIA release — dispatch logs (CAD)",
      type: "Public Record",
      source: "Cedar Hollow PD",
      date: "2025-04-30",
      pages: 11,
      event: "e13",
      tags: ["foia", "dispatch", "cad"],
      summary:
        "Computer-aided-dispatch logs and timestamps for the March 12 response.",
    },
    {
      id: "d10",
      title: "FOIA release — body-worn camera index",
      type: "Public Record",
      source: "Cedar Hollow PD",
      date: "2025-04-30",
      pages: 5,
      event: "e13",
      tags: ["foia", "bodycam", "index"],
      summary:
        "Index and chain-of-custody sheet for the six released bodycam files.",
    },
    {
      id: "d11",
      title: "Cedar Hollow Courier — records request",
      type: "FOIA Request",
      source: "The Cedar Hollow Courier",
      date: "2025-03-19",
      pages: 2,
      event: "e8",
      tags: ["foia", "request"],
      summary:
        "The public-records request that surfaced the incident report and later footage.",
    },
    {
      id: "d12",
      title: "City council agenda — filming policy item",
      type: "Public Record",
      source: "City of Cedar Hollow",
      date: "2025-05-20",
      pages: 8,
      event: "e15",
      tags: ["council", "agenda"],
      summary:
        "Council agenda packet including the commercial-premises filming-policy discussion item.",
    },
  ];

  // ---------- SOCIAL ----------
  const social = [
    {
      id: "s1",
      platform: "X",
      author: "@curb_authority",
      handle: "Reese Avila",
      date: "2025-03-04",
      text: "They told me I can't film in a store that's open to the public. Full video dropping tonight. ⬇️",
      likes: "48.2K",
      reposts: "12.1K",
      replies: "3.4K",
      event: "e1",
      verified: true,
    },
    {
      id: "s2",
      platform: "Reddit",
      author: "u/hollow_local",
      handle: "r/CedarHollow",
      date: "2025-03-05",
      text: "Anyone know what actually happened at the Cogwheel on Maple? Seeing clips everywhere.",
      likes: "2.1K",
      reposts: "—",
      replies: "640",
      event: "e1",
    },
    {
      id: "s3",
      platform: "TikTok",
      author: "@clipwatch",
      handle: "ClipWatch",
      date: "2025-03-05",
      text: "The Cogwheel filming situation explained in 60 seconds #cedarhollow",
      likes: "212K",
      reposts: "31K",
      replies: "8.9K",
      event: "e1",
    },
    {
      id: "s4",
      platform: "X",
      author: "@cogwheelbrands",
      handle: "Cogwheel Brands",
      date: "2025-03-14",
      text: "We are aware of an incident at an independently owned franchise location. A statement is on our site. We do not condone harassment of any kind.",
      likes: "9.8K",
      reposts: "2.2K",
      replies: "14.7K",
      event: "e6",
      verified: true,
    },
    {
      id: "s5",
      platform: "Instagram",
      author: "@cedarhollowcourier",
      handle: "Cedar Hollow Courier",
      date: "2025-03-20",
      text: "Our reporter Sam Okafor breaks down what the records actually show. Link in bio.",
      likes: "14.3K",
      reposts: "—",
      replies: "1.1K",
      event: "e8",
      verified: true,
    },
    {
      id: "s6",
      platform: "X",
      author: "@curb_authority",
      handle: "Reese Avila",
      date: "2025-03-25",
      text: "We filed today. The complaint and every exhibit are public. Read them yourself before forming an opinion.",
      likes: "61.7K",
      reposts: "18.9K",
      replies: "5.2K",
      event: "e9",
      verified: true,
    },
    {
      id: "s7",
      platform: "YouTube",
      author: "Open Footage",
      handle: "Community post",
      date: "2025-05-08",
      date2: true,
      text: "Frame-by-frame bodycam breakdown is live. We synced both units to the dispatch timestamps.",
      likes: "33.4K",
      reposts: "—",
      replies: "2.7K",
      event: "e14",
    },
    {
      id: "s8",
      platform: "Facebook",
      author: "Cedar Hollow Community Board",
      handle: "Group · 42K members",
      date: "2025-04-02",
      text: "The legal fund for the filming case crossed its first goal. Mixed feelings in the comments here.",
      likes: "4.6K",
      reposts: "1.3K",
      replies: "2.9K",
      event: "e10",
    },
    {
      id: "s9",
      platform: "X",
      author: "@hollowcountyda",
      handle: "Hollow County DA",
      date: "2025-04-16",
      text: "After review, our office will not pursue charges arising from the March 12 call. Full memo attached.",
      likes: "7.1K",
      reposts: "1.9K",
      replies: "6.3K",
      event: "e12",
      verified: true,
    },
    {
      id: "s10",
      platform: "Reddit",
      author: "u/foia_friend",
      handle: "r/PublicRecords",
      date: "2025-04-30",
      text: "Full FOIA dump is out — CAD logs + 6 bodycam files. Mirrored everything in the archive. Links inside.",
      likes: "5.4K",
      reposts: "—",
      replies: "910",
      event: "e13",
    },
    {
      id: "s11",
      platform: "TikTok",
      author: "@signalnoise",
      handle: "Signal & Noise",
      date: "2025-05-10",
      text: "Why did THIS become a national story? A media-dynamics breakdown. #mediaanalysis",
      likes: "189K",
      reposts: "22K",
      replies: "7.4K",
      event: "e14",
    },
    {
      id: "s12",
      platform: "X",
      author: "@nandakumarlaw",
      handle: "Nandakumar Law",
      date: "2025-04-12",
      text: "We've responded to opposing counsel's letter. Our client's right to document in public spaces is not in question.",
      likes: "12.9K",
      reposts: "3.1K",
      replies: "1.8K",
      event: "e11",
      verified: true,
    },
  ];

  const platforms = [
    "X",
    "Reddit",
    "TikTok",
    "Instagram",
    "Facebook",
    "YouTube",
  ];
  const docTypes = [
    "Court Filing",
    "Police Report",
    "FOIA Request",
    "Correspondence",
    "Legal Notice",
    "Statement",
    "Public Record",
  ];

  function eventById(id) {
    return events.find((e) => e.id === id);
  }
  function personById(id) {
    return people.find((p) => p.id === id);
  }

  return {
    CATS,
    stats,
    people,
    events,
    videos,
    bodycam,
    documents,
    social,
    platforms,
    docTypes,
    eventById,
    personById,
    links: { youtube: "#", gofundme: "#" },
  };
})();
